web_extra_exposed_ports:
    - name: gatsby
      container_port: 8000
      http_port: 80
      https_port: 443
web_extra_daemons:
    - name: gatsby
      command: '/var/www/html/.ddev/commands/web/gatsby.sh'
      directory: /var/www/html
web_environment:
    - GATSBY_DISABLE_ESLINT=true
